[%General]
#界面风格，预留
style_mode=0

#程序运行名称，为了通过FindWindow函数查找
local_window_name=Bend_OCR_System
comm_window_name=prodove_comm

#共享内存
to_plc_share_mem_name=MEM_L2_PLC_COMM
from_plc_share_mem_name=MEM_PLC_L2_COMM

#工位数量
work_station_num=1

#界面刷新时间与采样时间
data_refresh_ms=200
data_refresh_s=2000
sample_period=200

#是否测试模式
test_mode=0

#是否保存录像
write_rot_video=0

[workstation1]
#序号
serialNumber=1
#工位位置：翻板台北   可选的值有：stagingSouth、stagingNorth、stackerTable、hotCharging
location=stackerTable
loop_refresh_ms=1000

##相机
Master_ip_addr=192.168.196.100
Master_sn=24368453
Slave_ip_addr=192.168.196.101
Slave_sn=24368461
front_camera_res_width=4096
front_camera_res_height=190
test_img_filename=test_north.jpg

##图像处理参数
mode=1   #debug-0  run-1
ocrBufferPath=D:/data/stackerTable/ocrBuffer
detBufferPath=D:/data/stackerTable/detBuffer
remotePath="\\\\192.168.0.195/Temp/"
#模型路径
det_model=PlateDetectionModel_0306.hdl
det_param=DetectionPreprocessParam_0306.hdict
ocr_det_1=detection_0125.hdl
ocr_det_2=detection.hdl
ocr_recog_2=recognition.hdl
#仿射变换坐标
affine_x_pre="3571,1359,-1178,373"
affine_y_pre="438,3668,3552,-331"
affine_x_post="1000,1000,0,0"
affine_y_post="0,2000,2000,0"
#区域轮廓
roi_region="0,0,900,2000"
#目标跟踪参数
max_age=1
min_hits=3
iouThreshold=0.7

##数据库
DbType=SQLSERVER
DbName=camber_control
HostName=127.0.0.1
HostPort=1433
UserName=sa
UserPwd=ralautomation
TableName=BufferData
KeyName=utc,recogID,path,error

##mqtt
mqtt_use=1
mqtt_trigger_time=200
mqtt_hostname=127.0.0.1
mqtt_port=1883
mqtt_save_image_path=D:/data/hard_samples
mqtt_image_cycle_num=50
mqtt_public_msg=ocr/stagingNorth/msg



[Db1Config]
DbType=SQLSERVER
DbName=camber_control
HostName=127.0.0.1
HostPort=1433
UserName=sa
UserPwd=ralautomation

#相机访问设定
[CameraFront]
front_ip_addr=172.166.111.233
#相机设定参数
front_expTime=17000
front_gain=0
front_frameRate=20
front_camera_res_width=4096
front_camera_res_height=2160

[CameraBack]
back_ip_addr=192.168.1.64
#相机设定参数
back_expTime=18000
back_gain=0
back_frameRate=20
back_camera_res_width=1280
back_camera_res_height=1024

#相机测量设定
[DetectGeneral]
calibrate_path=image_calibrate
test_path=image_test
save_path=E:/HeadData/image_data

[Img]
save_path=D:/data/buffer_imgs/

[Stitch]
; 横向物理偏移(mm)
OffsetX=1825.0
; 纵向错位公差(mm)
OffsetY=2.0
; 像素当量(mm/px)
Scale=0.659
; 拼接后的画布总宽度(像素)，4500mm / 0.659 ≈ 6828
TotalWidth=6828
; 画布高度
TotalHeight=3300

[MQTT]
mqtt_use=1
mqtt_trigger_time=200
mqtt_hostname=127.0.0.1
mqtt_port=1883
mqtt_save_image_path=D:/data/hard_samples/
mqtt_image_cycle_num=50

[JK]
ip=192.168.1.64
port=8000
user=admin
password=ral325..
